### PR TITLE
Add multi select to see multiple subreddits at once

### PR DESCRIPTION
**Pull request by rendely**
### Description

These changes add a multi select search, letting users view multiple visual subreddits at once. 

### Screenshot

https://imgur.com/a/OwfNYBl

### CODE REVIEW

**Comment by rendely** [comment]
Hey there, feel free to reject this change or request any cleanup. I'm learning to code and was using this is a practice opportunity. Appreciate any tips on improvement!

**Review by gregrickaby — CHANGES_REQUESTED** [review]
@rendely I really, really like this idea! Would you mind running your PR through prettier first? 

Just run `npm run format` and commit those changes.

Thank you.

**Comment by rendely** [comment]
Absolutely, let me know if that worked!

**Comment by rendely** [comment]
Just checking back in if anything else needed from my side

**Review by gregrickaby — APPROVED** [review]
@rendely Sorry for the delay. Started a new job and have been totally immersed in it.

As I said, I love this approach. LGTM!

**Pull request merged**
